---
title: "Domáca úloha 1"
output: 
    html_document: 
      theme: united
      highlight: espresso
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Pokyny

* Úlohu vypracováva každý samostatne alebo v dvojici. Komunikácia ohľadom riešenia, zdieľanie kódu a pod. je zakázaná. Pri odpísaní úlohy alebo jej časti je DÚ hodnotená 0 bodmi, a to aj pre tých, **ktorí úlohu odpísali aj pre tých, ktorí ju dali odpísať.**

* Úlohu posielajte elektronicky na adresu alexbabis96@gmail.com s predmetom **CR 2021 - DU1 - priezvisko/priezviská** 

* Body za DÚ dostanete mailom. V prípade, že úlohu riešite v skupine, pri odovzdávaní pošlite kópiu mailu aj ostatným členom skupiny, aby aj oni dostali informáciu o hodnotení, keď ju budem posielať pomocou reply all. Ak to nespravíte, je vašou úlohou informovať kolegov o bodoch.

* Posielajte vypracovanú úlohu v pdf formáte (súvislý, dobre čitateľný text doplnený grafmi, nie iba výstupy z R so stručnými poznámkami) a použitý kód ako samostatný súbor. Môžete použiť aj R markdown s HTML výstupom, kde spojíte kompletný kód a sprievodný text, v tom prípade posielajte vygenerovaný dokument.

* V oboch príkladoch pracuje každá skupina s inými dátami, rezervácia dát na stránke (píšte svoje meno/mená a názov akcie, resp. názov dát a zdroj pre Bassov model, neuvádzajte svoj e-mail) https://docs.google.com/spreadsheets/d/1gnfxc4rRPzlymTKibpxufYRg6SVtHchX7mZiKrp4s_o/edit#gid=0

# Testovanie autokorelácií (6 Bodov)

* Pracovať budete s knížnicou `quantmod` (tak ako sme to robili na cvičení). Každá skupina/jedinec si stiahne dáta o nejakej firme. `Symbols` (tá skratka danej firmy, ktorú budete potrebovať použiť vo funkcií `getSymbols`) sa dá nájsť pre konkrétne firmy napríklad tak, že si názov firmy napíšete do https://finance.yahoo.com/

* Dáta si môžete stiahnúť za ľubovoľné obdobie, ale nech mate aspoň jeden rok dát

* Pracovať budete s posledným stĺpcom `Adjusted`. Transformujte dáta najskôr na týždenné (na cvičení sme mali ako sa transformujú na mesačné) a vypočítajte logartmické výnosy.

* Náplň prvej úlohy bude testovanie pomocou ACF a Ljung-Boxovho testu, že tieto výnosy sa dajú modelovať ako konštanta (stredná hodnota výnosov - tá na autokorelácie nemá vplyv) plus biely šum.

* Za tieto časti získate body: (Za každú 1)
    + Názov zvolenej firmy, krátka informácia o nej
    + Grafy priebehu cien akcie a výnosov (použite grafy z knižnice `quantmod`)
    + Zobrazenie výberovej autokorelačnej funkcie výnosov a jej interpretáciu.
    + Pomocou príkazu `acf(y, plot = FALSE, lag.max = 10)` - (y sú vaše dáta) - dostanete prvých 10 hodnôt autokorelačnej funkcie. Pomocou **týchto zaokrúhlených hodnôt** testujte hypotézu, že prvé 3 autokorelácie sú nulové. Vypočítajte pomocou R-ka (bez použitia funkcie `Box.test`) hodnotu testovej štatistiky, kritickú hodnotu tohto testu na 5-percentnej hladine významnosti, p-value. Uvedte, či danú hypotézu zamietate/nezamietate a prečo. (Hodiť sa vám pri tom môže toto https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/Chisquare)
    + Výsledky Ljung-Boxovho testu pre hodnoty lagu od 1 až po zvolenú hornú hranicu (aspoň 8 lagov). P hodnoty znázornite graficky ako na cvičení, spolu s porovnaním s hodnotou 0.05. Interpretujte výsledky. (Tu už môžete použiť funkcie `Box.test`)
    + Zhodnotenie modelu: Považujete model "výnosy sú konštanta (t. j. priemerný výnos) plus biely šum" za dobrý model pre vaše dáta? Prečo?
    
# Bassov model (4 body)

Opäť si každá dvojica/jedinec nájde dáta, pričom nesmú byť rovnaké ako majú vaši kolegovia. Taktiež to nesmú byť dáta, s ktorými sme pracovali na cvičeniach.(Môžete si napríklad nájsť dáta o inom filme, ktorý na cvičení uvedený nebol)

* Body budete získavať za: (Za každú 1)
    + Krátky popis dát a uvedenie zdroja
    + Určenie dobrých začiatočných hodnôt pre prílušné parametre (také, aby vám metóda nls konvergovala)
    + Odhadnutie hodnôt parametrov pre vaše dáta 
    + Porovnanie skutočných tržieb s fitovanými + predikcie tržieb aspoň na 4 roky dopredu, aj s grafickým znázornením ($m*f(t)$ vs predaje, $m*F(t)$ vs kumulatívne predaje[funkcia `cumsum(x)`])
    
# Bonus (2 body)

* Odvodte vzťahy pre funkcie $f(t)$ a $F(t)$
    + (Návod: rozklad na parciálne zlomky)
$$
\begin{aligned}
 \frac{1}{(1-F(t))(p+qF(t))} = \frac{A}{(1-F(t))}+\frac{B}{p+qF(t)}
\end{aligned}
$$

* Dokážte, že ak $q>p>0$, tak funkcia $f(t)$ nadobúda maximum v čase
$$
\begin{aligned}
 t^{*}=\frac{ln(\frac{q}{p})}{p+q}
\end{aligned}
$$
    Voľne povedané, je to čas, v ktorom sa predá najviac výrobkov
    
* Odvodte vzťah pre maximum funkcie $f(t)$ v prípade, že $p>q>0$. Čo od tohto prípade - keď prevláda vplyv inovátorov - očakávame?

Bonus môžete počitať na papier, naskenovať ho a poslať ho zvlásť ako obrázky. Píšte ale čitateľne.