---
title: "Casove Rady 2021"
output: 
  html_document:
    theme: flatly
    highlight: zenburn
---

<style type="text/css">
.title {
  display: none;
}

#getting-started img {
  margin-right: 10px;
}

</style>

<div class="row" style="padding-top: 30px;">
<div class="col-sm-6">

# **Časové Rady 2021**

Vítajte na stránke pre cvičenia z časových radov 2021.

V záložke Tutorials nájdete materiály k cvičeniam. 

V záložke Homeworks nájdete zadania domácich úloh.

```{r include = FALSE}

cvicenia <- data.frame(Index = paste0("Cvičenie ",c(1:6)),
                       Datum = c("27.09.-01.09.2021",
                                 "18.10.-22.10.2021",
                                 "25.10.-29.10.2021",
                                 "08.11.-12.11.2021",
                                 "22.11.-26.11.2021",
                                 "29.11.-03.12.2021"),
                       Domaca_uloha = c("Áno","Nie",
                                        "Áno","Áno",
                                        "Áno","Áno"),
                       Miestnost = c("M-208",
                                    "M-208",
                                    "M-X",
                                    "M-208",
                                    "M-208",
                                    "M-208"),
                       Deadline = c("15.10.2021-24:00",
                                    "",
                                    "12.11.2021-24:00",
                                    "25.11.2021-24:00",
                                    "09.12.2021-24:00",
                                    "17.12.2021-24:00"))
colnames(cvicenia) <- c("Poradie","Týždeň",
                        "Domáca úloha",
                        "Miestnosť", "Deadline pre DÚ")
```

```{r echo = FALSE, results='asis'}
library(knitr)
kable(cvicenia[,c(1,2,4,3,5)], caption = "Tabuľka cvičení")
```

