<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Cvičenie 4 - Zostavenie a testovanie ARIMA modelov</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  { color: #cccccc; background-color: #303030; }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ffcfaf; } /* Alert */
code span.an { color: #7f9f7f; font-weight: bold; } /* Annotation */
code span.at { } /* Attribute */
code span.bn { color: #dca3a3; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #f0dfaf; } /* ControlFlow */
code span.ch { color: #dca3a3; } /* Char */
code span.cn { color: #dca3a3; font-weight: bold; } /* Constant */
code span.co { color: #7f9f7f; } /* Comment */
code span.cv { color: #7f9f7f; font-weight: bold; } /* CommentVar */
code span.do { color: #7f9f7f; } /* Documentation */
code span.dt { color: #dfdfbf; } /* DataType */
code span.dv { color: #dcdccc; } /* DecVal */
code span.er { color: #c3bf9f; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #c0bed1; } /* Float */
code span.fu { color: #efef8f; } /* Function */
code span.im { } /* Import */
code span.in { color: #7f9f7f; font-weight: bold; } /* Information */
code span.kw { color: #f0dfaf; } /* Keyword */
code span.op { color: #f0efd0; } /* Operator */
code span.ot { color: #efef8f; } /* Other */
code span.pp { color: #ffcfaf; font-weight: bold; } /* Preprocessor */
code span.sc { color: #dca3a3; } /* SpecialChar */
code span.ss { color: #cc9393; } /* SpecialString */
code span.st { color: #cc9393; } /* String */
code span.va { } /* Variable */
code span.vs { color: #cc9393; } /* VerbatimString */
code span.wa { color: #7f9f7f; font-weight: bold; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h2 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h3 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h4 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h5 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h6 {
  padding-top: 65px;
  margin-top: -65px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Časové rady</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Tutorials
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Cvicenie1.html">Tutorial 1</a>
    </li>
    <li>
      <a href="Cvicenie2.html">Tutorial 2</a>
    </li>
    <li>
      <a href="Cvicenie3.html">Tutorial 3</a>
    </li>
    <li>
      <a href="Cvicenie4.html">Tutorial 4</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Homeworks
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Domaca_uloha1.html">Homework 1</a>
    </li>
    <li>
      <a href="Domaca_uloha2.html">Homework 2</a>
    </li>
    <li>
      <a href="Domaca_uloha3.html">Homework 3</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Cvičenie 4 - Zostavenie a testovanie ARIMA modelov</h1>

</div>


<div id="potrebé-knižnice-pre-cvičenie-4" class="section level1">
<h1><span class="header-section-number">1</span> Potrebé knižnice pre cvičenie 4</h1>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" title="1"><span class="kw">library</span>(astsa)</a>
<a class="sourceLine" id="cb1-2" title="2"><span class="kw">library</span>(urca)</a>
<a class="sourceLine" id="cb1-3" title="3"><span class="kw">library</span>(ggfortify)</a>
<a class="sourceLine" id="cb1-4" title="4"><span class="kw">library</span>(ggplot2)</a></code></pre></div>
</div>
<div id="minimálna-kostra---príklad-2" class="section level1">
<h1><span class="header-section-number">2</span> Minimálna kostra - príklad 2</h1>
<p>Cieľom bude nájdenie vhodného ARIMA modelu pre dáta (na skúške bývajú dáta, ako tieto naše, ktoré sa dajú modelovať ako ARIMA proces, pričom p ani q nie sú väčšie ako 5)</p>
<p>Majme data z knižnice <code>astsa</code>:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" title="1">y &lt;-<span class="st"> </span><span class="kw">ts</span>(econ5<span class="op">$</span>unemp, </a>
<a class="sourceLine" id="cb2-2" title="2">        <span class="dt">frequency =</span> <span class="dv">4</span>, <span class="dt">start =</span> <span class="kw">c</span>(<span class="dv">1950</span>,<span class="dv">1</span>), <span class="dt">end =</span> <span class="kw">c</span>(<span class="dv">1969</span>, <span class="dv">4</span>))</a>
<a class="sourceLine" id="cb2-3" title="3"><span class="kw">autoplot</span>(y)</a></code></pre></div>
<p><img src="Cvicenie4_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>Zadanie bude nasledovné:</p>
<ul>
<li>Vysvetlite koľko krát a prečo sa majú dáta diferencovať. Čiže pre každý časový rad (pôvodné dáta, prvé diferencie, druhé diferencie, …) napíšte, či ste dáta diferencovali a prečo. Skončite tým, že určitý časový rad nebude treba už viac diferencovať</li>
<li>Testovanie jednotkového koreňa. V poslednom kroku nastala situácia, že v dátach nebol trend, ani jednotkový koreň, a preto ich nebolo nutné diferencovať. Podrobne vysvetlite, čo sa tam dialo:<br />
Napíšte s akými parametrami ADF testu ste dáta testovali a aká regresia sa tam odhadla.
<ol style="list-style-type: decimal">
<li>Aká hypotéza o koeficientoch regresie sa testuje?</li>
<li>Odvoďte, že táto hypotéza predstavuje hypotézu o jednotkovom koreni daného časového radu.</li>
<li>Kedy túto hypotézu zamietame (ako vyzerá kritériu založené na testovej štatistike a kritickej hodnote)?</li>
<li>Čo vyšlo v našom prípade (zamietame vs. nezamietame), čo to znamená pre diferencovanie nášho časového radu (diferencovať vs. nediferencovať)?</li>
</ol></li>
<li>Nájdite vhodný ARIMA model pre dáta <code>y</code>. Požiadavky sú: stacionarita, invertovateľnosť a p-hodnoty Ljung-Boxovho testu nad 5%.</li>
</ul>
<p>Riešenie:</p>
<ul>
<li>Dáta podľa grafu nevykazujú prítomnosť trendu. To znamená, že dáta <code>y</code> otestujeme už iba na prítomnosť jednotkového koreňa. Stredná hodnota dát vyzerá byť niekde v okolí hodnoty 5, preto zvolíme <code>type = "drift"</code>. Je dôležité zvoliť primeraný počet lagov,aby sa nám nestalo, že všetky lagy sa nám dostanú do výsledného modelu. V takom prípade nevieme, či je to najlepší možný model pre naše dáta podľa IC alebo sme ho dostali iba kvôli tomu, že sme väčší počet lagov nepovolili. V našom prípade zvolíme <code>lags = 4</code>. IC zvolíme napríklad <code>selectlags = "BIC"</code>.</li>
</ul>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" title="1"><span class="kw">summary</span>(<span class="kw">ur.df</span>(y, <span class="dt">lags =</span> <span class="dv">5</span>, <span class="dt">selectlags =</span> <span class="st">&quot;BIC&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;drift&quot;</span>))</a></code></pre></div>
<pre><code>## 
## ############################################### 
## # Augmented Dickey-Fuller Test Unit Root Test # 
## ############################################### 
## 
## Test regression drift 
## 
## 
## Call:
## lm(formula = z.diff ~ z.lag.1 + 1 + z.diff.lag)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.46609 -0.30430  0.02727  0.27560  1.31635 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.73035    0.22553   3.238 0.001829 ** 
## z.lag.1     -0.15690    0.04495  -3.490 0.000833 ***
## z.diff.lag   0.47941    0.09824   4.880  6.3e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4684 on 71 degrees of freedom
## Multiple R-squared:  0.2945, Adjusted R-squared:  0.2747 
## F-statistic: 14.82 on 2 and 71 DF,  p-value: 4.176e-06
## 
## 
## Value of test-statistic is: -3.4904 6.281 
## 
## Critical values for test statistics: 
##       1pct  5pct 10pct
## tau2 -3.51 -2.89 -2.58
## phi1  6.70  4.71  3.86</code></pre>
<ul>
<li><p>V dátach teda nie je prítomný jednotkový koreň (test ho zamietol na hladine významnosti 5%), preto ich nebudeme ďalej diferencovať.</p></li>
<li><p>Regresia, ktorá sa odhadla v teste <span class="math display">\[ \Delta z_{t} = \alpha + c_{1}z_{t-1}+c_{2}\Delta z_{t-1} + e_{t}\]</span></p></li>
<li><p>Hypotéza, ktorá sa testuje pre koeficienty z regresie <span class="math display">\[ H_{0}: c_{1} = 0 \;vs\; H_{1}: c_{1} &lt; 0 \]</span></p></li>
<li><p>Odvodenie, že hypotéza predstavuje aj hypotézu o jednotkovom koreni daného časového radu <span class="math display">\[ \Delta z_{t} = \alpha + c_{1}z_{t-1}+c_{2}\Delta z_{t-1} + e_{t}\]</span> <span class="math display">\[ z_{t}- z_{t-1}= \alpha + c_{1}z_{t-1}+c_{2}(z_{t-1}-z_{t-2}) + e_{t}\]</span> <span class="math display">\[ z_{t}= \alpha + (1+c_{1}+c_{2})z_{t-1}+(-c_{2})z_{t-2} + e_{t}\]</span> <span class="math display">\[ [1-(1+c_{1}+c_{2})L+c_{2}L^{2}]z_{t}= \alpha + e_{t}\]</span></p></li>
</ul>
<p>Ak by daný polynóm <span class="math inline">\(1-(1+c_{1}+c_{2})L+c_{2}L^{2}\)</span> mal jednotkový koreň, platilo by <span class="math display">\[1-(1+c_{1}+c_{2})+c_{2} = 0 \]</span> respektíve <span class="math display">\[-(1+c_{1}+c_{2})+c_{2} = -1 \]</span> z čoho po úprave dostávame, že <span class="math inline">\(c_{1} = 0\)</span>. Vidíme, že hypotéza o testovaní koeficientu <span class="math inline">\(c_{1}\)</span> z regresie, je totožná s hypotézou o testovaní jednotkového koreňa.</p>
<ul>
<li><p>Hypotézu zamietame ak je testová štatistika (<code>test-statistic is: -3.4904</code>) menšia ako sú kritické hodnoty(pre náš prípad máme kritické hodnoty dané):<br />
<code>##       1pct  5pct 10pct</code><br />
<code>## tau2 -3.51 -2.89 -2.58</code><br />
</p></li>
<li><p>V našom prípade výšlo, že testová štatistika je na hladine významnosti 5% menšia ako kritická hodnota, z toho dôvodu zamietame hypotézu <span class="math inline">\(H_{0}\)</span> a prijímame hypotézu <span class="math inline">\(H_{1}\)</span>. Znamená to, že v dátach nie je prítomný jednotkový koreň, teda dáta nemusíme diferencovať.</p></li>
<li><p>Hľadanie vhodného ARIMA modelu</p></li>
</ul>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" title="1"><span class="kw">acf2</span>(y)</a></code></pre></div>
<p><img src="Cvicenie4_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre><code>##      [,1]  [,2]  [,3] [,4] [,5]  [,6] [,7]  [,8] [,9] [,10] [,11] [,12] [,13]
## ACF  0.89  0.67  0.44 0.25 0.13  0.08 0.07  0.07 0.08  0.08  0.06  0.04  0.03
## PACF 0.89 -0.51 -0.06 0.10 0.13 -0.06 0.04 -0.08 0.14 -0.12  0.02 -0.01  0.08
##      [,14] [,15] [,16] [,17] [,18] [,19]
## ACF   0.02  0.04  0.08  0.10  0.08  0.02
## PACF -0.04  0.12 -0.01 -0.04 -0.19 -0.03</code></pre>
<ul>
<li>Podľa ACF/PACF vyzerá, že vhodný model pre naše dáta by mohol byť AR(2). Dôvod je ten, že PACF(k), pre k &gt; 2 vyzerá byť nulová a ACF je nenulová a postupne klesá.</li>
</ul>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" title="1">model.y &lt;-<span class="st"> </span><span class="kw">capture.output</span>(<span class="kw">sarima</span>(y,<span class="dv">2</span>,<span class="dv">0</span>,<span class="dv">0</span>)) <span class="co"># ked chceme iba grafy a nevypisovat konvergenciu ani summary modelu</span></a></code></pre></div>
<p><img src="Cvicenie4_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" title="1">model.y &lt;-<span class="st"> </span><span class="kw">sarima</span>(y,<span class="dv">2</span>,<span class="dv">0</span>,<span class="dv">0</span>, <span class="dt">details =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb8-2" title="2">model.y</a></code></pre></div>
<pre><code>## $fit
## 
## Call:
## stats::arima(x = xdata, order = c(p, d, q), seasonal = list(order = c(P, D, 
##     Q), period = S), xreg = xmean, include.mean = FALSE, transform.pars = trans, 
##     fixed = fixed, optim.control = list(trace = trc, REPORT = 1, reltol = tol))
## 
## Coefficients:
##          ar1      ar2   xmean
##       1.3667  -0.5336  4.7582
## s.e.  0.0928   0.0933  0.3057
## 
## sigma^2 estimated as 0.2162:  log likelihood = -53.39,  aic = 114.77
## 
## $degrees_of_freedom
## [1] 77
## 
## $ttable
##       Estimate     SE t.value p.value
## ar1     1.3667 0.0928 14.7222       0
## ar2    -0.5336 0.0933 -5.7183       0
## xmean   4.7582 0.3057 15.5676       0
## 
## $AIC
## [1] 1.434655
## 
## $AICc
## [1] 1.438602
## 
## $BIC
## [1] 1.553756</code></pre>
<p>P-hodnoty Ljung-Boxovho testu sú viac ako 5%. Invertovateľnosť netreba overovať, keďže nemáme MA členy. Overíme ešte stacionaritu.<br />
</p>
<p>Budeme počítať korene polynómu <span class="math inline">\(1-1.3667L + 0.5336 L^{2} = 0\)</span>, pričom tieto musia byť mimo jednotkový kruh.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" title="1"><span class="kw">polyroot</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="op">-</span><span class="fl">1.3667</span>,<span class="fl">0.5336</span>))</a></code></pre></div>
<pre><code>## [1] 1.280641+0.483758i 1.280641-0.483758i</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" title="1"><span class="kw">abs</span>(<span class="kw">polyroot</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="op">-</span><span class="fl">1.3667</span>,<span class="fl">0.5336</span>)))</a></code></pre></div>
<pre><code>## [1] 1.368964 1.368964</code></pre>
<p>2 komplexne združené korene v absolútnej hodnote viac ako 1, máme stacionárny proces.</p>
<div id="rovnaký-koreň-pre-oba-polynómy" class="section level2">
<h2><span class="header-section-number">2.1</span> Rovnaký koreň pre oba polynómy</h2>
<p>Modelujme predchadzajúce dáta ako ARMA(3,1) proces</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" title="1">model.y &lt;-<span class="st"> </span><span class="kw">capture.output</span>(<span class="kw">sarima</span>(y,<span class="dv">3</span>,<span class="dv">0</span>,<span class="dv">1</span>)) <span class="co"># ked chceme iba grafy a nevypisovat konvergenciu ani summary modelu</span></a></code></pre></div>
<p><img src="Cvicenie4_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" title="1">model.y &lt;-<span class="st"> </span><span class="kw">sarima</span>(y,<span class="dv">3</span>,<span class="dv">0</span>,<span class="dv">1</span>, <span class="dt">details =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb15-2" title="2">model.y</a></code></pre></div>
<pre><code>## $fit
## 
## Call:
## stats::arima(x = xdata, order = c(p, d, q), seasonal = list(order = c(P, D, 
##     Q), period = S), xreg = xmean, include.mean = FALSE, transform.pars = trans, 
##     fixed = fixed, optim.control = list(trace = trc, REPORT = 1, reltol = tol))
## 
## Coefficients:
##          ar1     ar2      ar3     ma1   xmean
##       0.4827  0.6355  -0.4290  0.9453  4.7569
## s.e.  0.1170  0.1323   0.1108  0.0560  0.3142
## 
## sigma^2 estimated as 0.2103:  log likelihood = -52.42,  aic = 116.84
## 
## $degrees_of_freedom
## [1] 75
## 
## $ttable
##       Estimate     SE t.value p.value
## ar1     0.4827 0.1170  4.1254   1e-04
## ar2     0.6355 0.1323  4.8038   0e+00
## ar3    -0.4290 0.1108 -3.8701   2e-04
## ma1     0.9453 0.0560 16.8952   0e+00
## xmean   4.7569 0.3142 15.1410   0e+00
## 
## $AIC
## [1] 1.460546
## 
## $AICc
## [1] 1.470681
## 
## $BIC
## [1] 1.639198</code></pre>
<p>Tento proces môžeme zapísať v tvare <span class="math display">\[(1-0.4827L - 0.6355 L^{2} +0.4290L^{3})y_{t} = \delta + (1+0.9453L)u_{t}\]</span></p>
<p>Spočítajme si korene daných polynómov:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" title="1"><span class="co"># alpha(L)</span></a>
<a class="sourceLine" id="cb17-2" title="2"><span class="kw">polyroot</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="op">-</span><span class="fl">0.4827</span>,<span class="op">-</span><span class="fl">0.6355</span>,<span class="fl">0.4290</span>))</a></code></pre></div>
<pre><code>## [1]  1.327070+0.475874i -1.172789+0.000000i  1.327070-0.475874i</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" title="1"><span class="co"># beta(L)</span></a>
<a class="sourceLine" id="cb19-2" title="2"><span class="kw">polyroot</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="fl">0.9453</span>))</a></code></pre></div>
<pre><code>## [1] -1.057865+0i</code></pre>
<p>Vykreslíme si ich do komplexnej roviny:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" title="1">phi &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">2</span><span class="op">*</span>pi, <span class="dt">length.out =</span> <span class="dv">100</span>)</a>
<a class="sourceLine" id="cb21-2" title="2">cos.phi &lt;-<span class="st"> </span><span class="kw">cos</span>(phi)</a>
<a class="sourceLine" id="cb21-3" title="3">sin.phi &lt;-<span class="st"> </span><span class="kw">sin</span>(phi)</a>
<a class="sourceLine" id="cb21-4" title="4"></a>
<a class="sourceLine" id="cb21-5" title="5">ar.poly &lt;-<span class="st"> </span><span class="kw">polyroot</span>(<span class="kw">c</span>(<span class="dv">1</span>, <span class="op">-</span>model.y<span class="op">$</span>fit<span class="op">$</span>coef[<span class="dv">1</span><span class="op">:</span><span class="dv">3</span>]))</a>
<a class="sourceLine" id="cb21-6" title="6">ma.poly &lt;-<span class="st"> </span><span class="kw">polyroot</span>(<span class="kw">c</span>(<span class="dv">1</span>, model.y<span class="op">$</span>fit<span class="op">$</span>coef[<span class="dv">4</span>]))</a>
<a class="sourceLine" id="cb21-7" title="7"><span class="kw">qplot</span>(cos.phi, sin.phi, <span class="dt">geom =</span> <span class="st">&quot;path&quot;</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb21-8" title="8"><span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">Re</span>(ar.poly), <span class="dt">y =</span> <span class="kw">Im</span>(ar.poly)), <span class="dt">color =</span> <span class="st">&quot;#D55E00&quot;</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb21-9" title="9"><span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">Re</span>(ma.poly), <span class="dt">y =</span> <span class="kw">Im</span>(ma.poly)), <span class="dt">color =</span> <span class="st">&quot;#009E73&quot;</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb21-10" title="10"><span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="dv">0</span>, <span class="dt">linetype =</span> <span class="st">&quot;dashed&quot;</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb21-11" title="11"><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>, <span class="dt">linetype =</span> <span class="st">&quot;dashed&quot;</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb21-12" title="12"><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&#39;Re&#39;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&#39;Im&#39;</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb21-13" title="13"><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">2</span>, <span class="dv">2</span>))<span class="op">+</span></a>
<a class="sourceLine" id="cb21-14" title="14"><span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">2</span>, <span class="dv">2</span>))</a></code></pre></div>
<p><img src="Cvicenie4_files/figure-html/unnamed-chunk-12-1.png" width="672" /> Korene AR a MA časti vyšli blízko seba, z toho vyplýva, že by sme mali o 1 znížiť rád AR aj MA členov.</p>
</div>
</div>
<div id="ďalšie-príklady" class="section level1">
<h1><span class="header-section-number">3</span> Ďalšie príklady</h1>
<p>Zopakujte postup vyššie pre nasledovné dáta:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" title="1"><span class="kw">library</span>(datasets)</a>
<a class="sourceLine" id="cb22-2" title="2">y &lt;-<span class="st"> </span>BJsales</a></code></pre></div>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" title="1"><span class="kw">data</span>(<span class="st">&quot;WWWusage&quot;</span>)</a>
<a class="sourceLine" id="cb23-2" title="2">y &lt;-<span class="st"> </span>WWWusage</a>
<a class="sourceLine" id="cb23-3" title="3"><span class="kw">plot</span>(y)</a></code></pre></div>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" title="1"><span class="kw">library</span>(datasets)</a>
<a class="sourceLine" id="cb24-2" title="2">y &lt;-<span class="st"> </span><span class="kw">window</span>(WWWusage, <span class="dt">start=</span><span class="dv">1</span>, <span class="dt">end=</span><span class="dv">70</span>)</a>
<a class="sourceLine" id="cb24-3" title="3"><span class="kw">plot</span>(y)</a></code></pre></div>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" title="1"><span class="kw">library</span>(astsa)</a>
<a class="sourceLine" id="cb25-2" title="2">y &lt;-<span class="st"> </span><span class="kw">window</span>(<span class="kw">log</span>(oil), <span class="dt">end=</span><span class="dv">2008</span>)</a>
<a class="sourceLine" id="cb25-3" title="3"><span class="kw">plot</span>(y)</a></code></pre></div>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" title="1"><span class="kw">library</span>(astsa)</a>
<a class="sourceLine" id="cb26-2" title="2">y &lt;-<span class="st"> </span><span class="kw">log</span>(gnp)</a>
<a class="sourceLine" id="cb26-3" title="3"><span class="kw">plot</span>(y)</a></code></pre></div>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" title="1"><span class="kw">library</span>(astsa)</a>
<a class="sourceLine" id="cb27-2" title="2">y &lt;-<span class="st"> </span><span class="kw">ts</span>(fmri<span class="op">$</span>L9T2[<span class="dv">1</span><span class="op">:</span><span class="dv">100</span>,<span class="dv">3</span>])</a>
<a class="sourceLine" id="cb27-3" title="3"><span class="kw">plot</span>(y)</a></code></pre></div>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" title="1"><span class="kw">library</span>(fpp)</a>
<a class="sourceLine" id="cb28-2" title="2"><span class="kw">data</span>(wmurders)</a>
<a class="sourceLine" id="cb28-3" title="3">y &lt;-<span class="st"> </span>wmurders</a>
<a class="sourceLine" id="cb28-4" title="4"><span class="kw">plot</span>(y)</a></code></pre></div>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" title="1"><span class="kw">library</span>(fpp)</a>
<a class="sourceLine" id="cb29-2" title="2"><span class="kw">data</span>(austa)</a>
<a class="sourceLine" id="cb29-3" title="3">y &lt;-<span class="st"> </span>austa</a>
<a class="sourceLine" id="cb29-4" title="4"><span class="kw">plot</span>(y)</a></code></pre></div>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" title="1"><span class="kw">library</span>(forecast)</a>
<a class="sourceLine" id="cb30-2" title="2">lambda &lt;-<span class="st"> </span><span class="kw">BoxCox.lambda</span>(usnetelec)</a>
<a class="sourceLine" id="cb30-3" title="3">y &lt;-<span class="st"> </span><span class="kw">BoxCox</span>(usnetelec, lambda)</a>
<a class="sourceLine" id="cb30-4" title="4"><span class="kw">plot</span>(y)</a></code></pre></div>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" title="1"><span class="kw">library</span>(forecast)</a>
<a class="sourceLine" id="cb31-2" title="2">lambda &lt;-<span class="st"> </span><span class="kw">BoxCox.lambda</span>(usgdp)</a>
<a class="sourceLine" id="cb31-3" title="3">y &lt;-<span class="st"> </span><span class="kw">BoxCox</span>(usgdp, lambda)</a>
<a class="sourceLine" id="cb31-4" title="4"><span class="kw">plot</span>(y)</a></code></pre></div>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" title="1"><span class="kw">library</span>(forecast)</a>
<a class="sourceLine" id="cb32-2" title="2">lambda &lt;-<span class="st"> </span><span class="kw">BoxCox.lambda</span>(mcopper)</a>
<a class="sourceLine" id="cb32-3" title="3">y &lt;-<span class="kw">BoxCox</span>(mcopper, lambda)</a>
<a class="sourceLine" id="cb32-4" title="4"><span class="kw">plot</span>(y)</a></code></pre></div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = false;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
